### ISSUE TITLE
The model of ReversibleGraphNet is not defined!

### ISSUE THREAD

**Issue by machanic** [hmdolatabadi/AdvFlow#1]
I want to find out what the invertable flow model is, I check the code in model.py
https://github.com/hmdolatabadi/AdvFlow/blob/master/model.py#L99
But the `ReversibleGraphNet ` is not defined and directly used.

**Comment by hmdolatabadi** [comment]
Hi there.

Thanks for your message. As I've put in the requirements.txt, you need to first install the FrEIA library. The `ReversibleGraphNet` comes directly from this library. Here is also the official repo of the library in case you want to directly download it: [FrEIA](https://github.com/VLL-HD/FrEIA )

**Comment by machanic** [comment]
Hi thanks for replying.
Can you explain your method a bit more to make easier to understand. Or some simple words for better understanding? It seems that this method is similar with TREMBA.

**Comment by machanic** [comment]
@hmdolatabadi Doesn't ReversibleGraphNet need to import statement?

**Comment by hmdolatabadi** [comment]
Thanks for your continued interest in my work.

1) Yes, it is similar, but not entirely. AFAIK, in TREMBA you train you AE network on a substitute classifier to generate adversarial examples. As such, if the target and substitute network use two different type of training (vanilla, adversarial, etc.) your performance is going to degrade. Here, I am using a flow-based model trained solely on clean data. Moreover, AdvFlow also has the advantage the it provides you with a an explicit likelihood model, which may be useful in treating adversarial vulnerability. I am planning to write a short, simple blogpost to publish it alongside the camera ready version. Stay tuned!

2) The `from FrEIA.framework import *` command will import the entire library, which contains the `ReversibleGraphNet`.

**Comment by machanic** [comment]
@hmdolatabadi Can you notify me if you write done the blog for the introdution? My email is sharpstill@163.com

**Comment by machanic** [comment]
`Moreover, AdvFlow also has the advantage that it provides you with a an explicit likelihood model`, the concept of likelihood model is maximum likelihood estimation (MLE) or (MAP)?

**Comment by machanic** [comment]
@hmdolatabadi Can you explain your code in attack.py or attack_greedy.py, because some codes do not consistent with the pseudo code of the paper.

**Comment by hmdolatabadi** [comment]
@machanic Thanks for you comments.
1) I will notify you once I wrote the blogpost.
2) By explicit likelihood model, I mean we have an estimate of the log-likelihood. As for pre-training the flow-based model, we are using MLE objective. Afterwards, however, we only change the base distribution by an affine transformation. This would change the distribution a bit, but overall it remains similar to the true distribution. Read Section 3.4.1 of the paper for a more thorough explanation.
3) They are consistent to the Algorithms. I think I would also add detailed comments to the code once I've had the time. Sorry, currently I am too busy with preparing the camera ready version.

**Comment by machanic** [comment]
To understand your paper and normalization flow,  I found a video of https://www.youtube.com/watch?v=i7LjDvsLWCg  
Does this video explain some aspects of your use of normalization flow?

**Comment by hmdolatabadi** [comment]
Yes, it almost covers it all.

**Comment by machanic** [comment]
I am re-reading your paper and I wonder how to improve your method.
Do you have some suggestions?

**Comment by hmdolatabadi** [comment]
Thanks for your patience.
The future directions are discussed in Section 5 of the paper.

BTW, I've added detailed comments (with pointers to Algorithm lines) to the code.
Also, you can now see the AdvFlow blogpost [here](https://hmdolatabadi.github.io/posts/2020/10/advflow/).
