### ISSUE TITLE
AttributeError: module 'config' has no attribute 'org_size'

### ISSUE THREAD

**Issue by Kitzzaaa** [hmdolatabadi/AdvFlow#11]
Hi,this problem arises  when I run attack_imagenet.py,how to solve it?

**Comment by hmdolatabadi** [comment]
Hi,

Thanks for your interest in our work.
According to the code, it seems like you haven't specified the `dataset = 'ImageNet'`.
See these lines:
https://github.com/hmdolatabadi/AdvFlow/blob/e679d873cb2edb6358b47b07152dcd8255d7bb3f/config.py#L45-L59
