### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './flows/cifar-10_6_blocks_Simple_Gaussian.pt'

### ISSUE THREAD

**Issue by Kitzzaaa** [hmdolatabadi/AdvFlow#12]

**Comment by hmdolatabadi** [comment]
Hi.

As specified in the ReadMe, you first need to download the pre-trained flow-based models which can be found here:
https://drive.google.com/file/d/18J8eh-KLaPq9vUe_TwhuQMBW4WKBVX0L/view?usp=sharing.

Thanks for your interest in our work.
Closing the issue for now.
Let me know if you have any questions.
