### ISSUE TITLE
Why doesn't this method compare with Bandits, P-RGF or other black-box attacks?

### ISSUE THREAD

**Issue by machanic** [hmdolatabadi/AdvFlow#2]
I read your paper, I notice that in the table, you only compare AdvFlow with Nattack. Why doesn't this method compare with Bandits, P-RGF or other famous black-box query-based attacks?

**Comment by hmdolatabadi** [comment]
Thanks for your continued interest in our work.
The camera ready version of the paper now includes SimBA, as well as Bandits that were also included in the previous version.
Also, in table 1 we solely compare AdvFlow with NATTACKs as we want to examine the distributional properties of the two approach. The methods that you mentioned do not fit a distribution to the data.
