### ISSUE TITLE
name 'glow_coupling_layer' is not defined

### ISSUE THREAD

**Issue by Asteriajojo** [hmdolatabadi/AdvFlow#5]
when I run attack_imagenet.py, it occurs error like this

Traceback (most recent call last):
  File "attack_imagenet.py", line 35, in <module>
    import model
  File "/opt/data/private/cvpr_attack/AdvFlow/model.py", line 25, in <module>
    glow_coupling_layer, {'clamp': c.clamping, 'F_class': F_conv,
NameError: name 'glow_coupling_layer' is not defined

Could you please tell me how to sovle this problem?
Thanks a lot!

**Comment by hmdolatabadi** [comment]
Hi!
Have you installed the FrEIA library?
It seems that you need to install it.
The instructions can be found on the requirements.txt

**Comment by Asteriajojo** [comment]
I have installed FrEIA library though the following way 
![image](https://user-images.githubusercontent.com/37069482/111107210-64091100-8591-11eb-9877-c07ff3e022de.png)
but still failed to find 'glow_coupling_layer' T^T
but if I change glow_coupling_layer to 'GLOWCouplingBlock',then it occurs mistake "name 'F_conv' is not defined"
I don't know what I need to do 😭

**Comment by hmdolatabadi** [comment]
OK, maybe there is some version mismatch happening.
Attached you can find the exact same FrEIA library that I've used for this repository.
[FrEIA.zip](https://github.com/hmdolatabadi/AdvFlow/files/6139015/FrEIA.zip)

**Comment by Asteriajojo** [comment]
> OK, maybe there is some version mismatch happening.
> Attached you can find the exact same FrEIA library that I've used for this repository.
> [FrEIA.zip](https://github.com/hmdolatabadi/AdvFlow/files/6139015/FrEIA.zip)

Thanks a lot!
It really works!
