### ISSUE TITLE
AttributeError: module 'config' has no attribute 'init_scale'

### ISSUE THREAD

**Issue by sunwanting1** [hmdolatabadi/AdvFlow#8]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/swt/pycharm-2019.3.5/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/swt/pycharm-2019.3.5/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/swt/AdvFlow/attack.py", line 32, in <module>
    import model
  File "/home/swt/pycharm-2019.3.5/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/swt/AdvFlow/model.py", line 106, in <module>
    init_model(model)
  File "/home/swt/AdvFlow/model.py", line 89, in init_model
    param.data = c.init_scale * torch.randn(param.data.shape).cuda()
AttributeError: module 'config' has no attribute 'init_scale'
***************************************************
 **I find 'init_scale'  in 'pre_training',when I run attack why it need the attribute   'init_scale'.

"elif mode == 'pre_training':

    train_from_scratch = True
    
    workers         = 1              # Dataloader workers
    batch_size      = 64             # Batch-size
    n_epochs        = 350            # Number of training epochs
    
    lr              = 1e-4           # Initial learning rate of the optimizer
    decay_by        = 0.01           # Learning rate decay
    weight_decay    = 1e-5           # Weight decay of the optimizer
    betas           = (0.9, 0.999)   # Beta parameters of the Adam optimizer
    n_its_per_epoch = 2 ** 10        # Maximum number of training iterations per epoch
    
    do_rev          = False          # Adding the reconstruction error to the objective
    do_fwd          = True           # The usual log-likelihood training
    
    **### init_scale      = 0.03**
    pre_low_lr      = 1
    latent_noise    = 0.1
"

**Comment by hmdolatabadi** [comment]
Hi!

Yes, you are right. There's no need for that during attack as we are loading the saved flow-based model parameters.
I added the init_model() function to the model.py as I was trying to also include some experiments with the random weights (see Table. 1 of the paper). But as you said, during performing AdvFlow with pre-trained models, there's no need for that.

Sincerely.
